### ISSUE TITLE
`mr-img` seems broken

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/mrjs#486]
Example https://docs.mrjs.io/doc/mr-a/#image-links

The image used to load, now I get an error message in the console:

![image](https://github.com/Volumetrics-io/mrjs/assets/6750584/9bbcb9d6-0502-47b3-80c1-92058d1c0342)

**Comment by hanbollar** [comment]
odd 🤔 , ill take a look and get this resolved today

**Comment by hanbollar** [comment]
this should be fixed now, going to do a quick once over in the docs repo again to confirm then will ping you on discord as a heads up ~

**Comment by hanbollar** [comment]
not resolved - still looking into

**Comment by hanbollar** [comment]
with https://github.com/Volumetrics-io/documentation/commit/e186536ee8b38f3171f8fea9b60b1529c539b017 in im going to manually update the dist locally in documentation as i work through the fix to not add too many additional prs to main for one problem

**Comment by hanbollar** [comment]
noting this here - the image is there i swear, it just doesnt show up nicely in the area bc of css changes that have happened since awhile ago and we havent updated those manual part of the docs - (hence https://docs.mrjs.io/doc/mr-img/ having the same image on it loaded the same way but off center) - i'll add the item in the list of things i'll be making nicer as part of https://github.com/Volumetrics-io/documentation/pull/19
