### ISSUE TITLE
Clipping and/or masking not applied to some elements

### ISSUE THREAD

**Issue by michaelthatsit** [Volumetrics-io/mrjs#505]
Just caught this issue on the landing page. as you can see, the blue example tiles aren't being masked or clipped. 

https://github.com/Volumetrics-io/mrjs/assets/19628643/1e56401a-8b00-448a-87fd-25f1b62c62ad

**Comment by takahirox** [comment]
My comments from discord.

Ah sorry, sounds like the problem comes from the recent changes. I can’t test right now because I have been running fever since last night but from the code I speculate a bug in masking system. I think we should traverse objects associated with an entity and set up materials for stencil like clipping system does but we seem to be missing it

This block is suspicious https://github.com/Volumetrics-io/mrjs/blob/d37a00a5b3faea4610676792f06321bbe053047a/src/core/componentSystems/MaskingSystem.js#L181

It would be needed to be rewrite with like https://github.com/Volumetrics-io/mrjs/blob/3cdbbcd10e3894873112be63d0c231ab8e4229fc/src/core/componentSystems/ClippingSystem.js#L94

**Comment by takahirox** [comment]
(Honestly I don't know why it worked before...)
